const deck = [
  {
    title: "2 of Hearts",
    value: 2,
    type: "Hearts",
    image: "https://example.com/images/2_of_hearts.png",
  },
  {
    title: "3 of Hearts",
    value: 3,
    type: "Hearts",
    image: "https://example.com/images/3_of_hearts.png",
  },
  {
    title: "4 of Hearts",
    value: 4,
    type: "Hearts",
    image: "https://example.com/images/4_of_hearts.png",
  },
  {
    title: "5 of Hearts",
    value: 5,
    type: "Hearts",
    image: "https://example.com/images/5_of_hearts.png",
  },
  {
    title: "6 of Hearts",
    value: 6,
    type: "Hearts",
    image: "https://example.com/images/6_of_hearts.png",
  },
  {
    title: "7 of Hearts",
    value: 7,
    type: "Hearts",
    image: "https://example.com/images/7_of_hearts.png",
  },
  {
    title: "8 of Hearts",
    value: 8,
    type: "Hearts",
    image: "https://example.com/images/8_of_hearts.png",
  },
  {
    title: "9 of Hearts",
    value: 9,
    type: "Hearts",
    image: "https://example.com/images/9_of_hearts.png",
  },
  {
    title: "10 of Hearts",
    value: 10,
    type: "Hearts",
    image: "https://example.com/images/10_of_hearts.png",
  },
  {
    title: "Jack of Hearts",
    value: 10,
    type: "Hearts",
    image: "https://example.com/images/jack_of_hearts.png",
  },
  {
    title: "Queen of Hearts",
    value: 10,
    type: "Hearts",
    image: "https://example.com/images/queen_of_hearts.png",
  },
  {
    title: "King of Hearts",
    value: 10,
    type: "Hearts",
    image: "https://example.com/images/king_of_hearts.png",
  },
  {
    title: "Ace of Hearts",
    value: [1, 11],
    type: "Hearts",
    image: "https://example.com/images/ace_of_hearts.png",
  },
  {
    title: "2 of Diamonds",
    value: 2,
    type: "Diamonds",
    image: "https://example.com/images/2_of_diamonds.png",
  },
  {
    title: "3 of Diamonds",
    value: 3,
    type: "Diamonds",
    image: "https://example.com/images/3_of_diamonds.png",
  },
  {
    title: "4 of Diamonds",
    value: 4,
    type: "Diamonds",
    image: "https://example.com/images/4_of_diamonds.png",
  },
  {
    title: "5 of Diamonds",
    value: 5,
    type: "Diamonds",
    image: "https://example.com/images/5_of_diamonds.png",
  },
  {
    title: "6 of Diamonds",
    value: 6,
    type: "Diamonds",
    image: "https://example.com/images/6_of_diamonds.png",
  },
  {
    title: "7 of Diamonds",
    value: 7,
    type: "Diamonds",
    image: "https://example.com/images/7_of_diamonds.png",
  },
  {
    title: "8 of Diamonds",
    value: 8,
    type: "Diamonds",
    image: "https://example.com/images/8_of_diamonds.png",
  },
  {
    title: "9 of Diamonds",
    value: 9,
    type: "Diamonds",
    image: "https://example.com/images/9_of_diamonds.png",
  },
  {
    title: "10 of Diamonds",
    value: 10,
    type: "Diamonds",
    image: "https://example.com/images/10_of_diamonds.png",
  },
  {
    title: "Jack of Diamonds",
    value: 10,
    type: "Diamonds",
    image: "https://example.com/images/jack_of_diamonds.png",
  },
  {
    title: "Queen of Diamonds",
    value: 10,
    type: "Diamonds",
    image: "https://example.com/images/queen_of_diamonds.png",
  },
  {
    title: "King of Diamonds",
    value: 10,
    type: "Diamonds",
    image: "https://example.com/images/king_of_diamonds.png",
  },
  {
    title: "Ace of Diamonds",
    value: [1, 11],
    type: "Diamonds",
    image: "https://example.com/images/ace_of_diamonds.png",
  },
  {
    title: "2 of Clubs",
    value: 2,
    type: "Clubs",
    image: "https://example.com/images/2_of_clubs.png",
  },
  {
    title: "3 of Clubs",
    value: 3,
    type: "Clubs",
    image: "https://example.com/images/3_of_clubs.png",
  },
  {
    title: "4 of Clubs",
    value: 4,
    type: "Clubs",
    image: "https://example.com/images/4_of_clubs.png",
  },
  {
    title: "5 of Clubs",
    value: 5,
    type: "Clubs",
    image: "https://example.com/images/5_of_clubs.png",
  },
  {
    title: "6 of Clubs",
    value: 6,
    type: "Clubs",
    image: "https://example.com/images/6_of_clubs.png",
  },
  {
    title: "7 of Clubs",
    value: 7,
    type: "Clubs",
    image: "https://example.com/images/7_of_clubs.png",
  },
  {
    title: "8 of Clubs",
    value: 8,
    type: "Clubs",
    image: "https://example.com/images/8_of_clubs.png",
  },
  {
    title: "9 of Clubs",
    value: 9,
    type: "Clubs",
    image: "https://example.com/images/9_of_clubs.png",
  },
  {
    title: "10 of Clubs",
    value: 10,
    type: "Clubs",
    image: "https://example.com/images/10_of_clubs.png",
  },
  {
    title: "Jack of Clubs",
    value: 10,
    type: "Clubs",
    image: "https://example.com/images/jack_of_clubs.png",
  },
  {
    title: "Queen of Clubs",
    value: 10,
    type: "Clubs",
    image: "https://example.com/images/queen_of_clubs.png",
  },
  {
    title: "King of Clubs",
    value: 10,
    type: "Clubs",
    image: "https://example.com/images/king_of_clubs.png",
  },
  {
    title: "Ace of Clubs",
    value: [1, 11],
    type: "Clubs",
    image: "https://example.com/images/ace_of_clubs.png",
  },
  {
    title: "2 of Spades",
    value: 2,
    type: "Spades",
    image: "https://example.com/images/2_of_spades.png",
  },
  {
    title: "3 of Spades",
    value: 3,
    type: "Spades",
    image: "https://example.com/images/3_of_spades.png",
  },
  {
    title: "4 of Spades",
    value: 4,
    type: "Spades",
    image: "https://example.com/images/4_of_spades.png",
  },
  {
    title: "5 of Spades",
    value: 5,
    type: "Spades",
    image: "https://example.com/images/5_of_spades.png",
  },
  {
    title: "6 of Spades",
    value: 6,
    type: "Spades",
    image: "https://example.com/images/6_of_spades.png",
  },
  {
    title: "7 of Spades",
    value: 7,
    type: "Spades",
    image: "https://example.com/images/7_of_spades.png",
  },
  {
    title: "8 of Spades",
    value: 8,
    type: "Spades",
    image: "https://example.com/images/8_of_spades.png",
  },
  {
    title: "9 of Spades",
    value: 9,
    type: "Spades",
    image: "https://example.com/images/9_of_spades.png",
  },
  {
    title: "10 of Spades",
    value: 10,
    type: "Spades",
    image: "https://example.com/images/10_of_spades.png",
  },
  {
    title: "Jack of Spades",
    value: 10,
    type: "Spades",
    image: "https://example.com/images/jack_of_spades.png",
  },
  {
    title: "Queen of Spades",
    value: 10,
    type: "Spades",
    image: "https://example.com/images/queen_of_spades.png",
  },
  {
    title: "King of Spades",
    value: 10,
    type: "Spades",
    image: "https://example.com/images/king_of_spades.png",
  },
  {
    title: "Ace of Spades",
    value: [1, 11],
    type: "Spades",
    image: "https://example.com/images/ace_of_spades.png",
  },
];

export { deck };
